services:
  postgres:
    image: pgvector/pgvector:pg16
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: rootpwd
      POSTGRES_DB: projeti
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
